### ISSUE TITLE
npm install error

### ISSUE THREAD

**Issue by swashcap** [MRN-Code/coins-validate#1]
I get this error when running `npm install` on [MRN-Code/coinstac-common](https://github.com/MRN-Code/coinstac-common).

* Node: 5.7.1
* NPM: 3.8.1

```shell
$ npm install

> git-validate@2.1.4 install /Users/creed/Sites/coinstac-common/node_modules/git-validate
> node bin/install

fs.js:584
  return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
                 ^

Error: ENOENT: no such file or directory, open '/Users/creed/Sites/coinstac-common/.git/hooks/pre-commit'
    at Error (native)
    at Object.fs.openSync (fs.js:584:18)
    at Object.fs.writeFileSync (fs.js:1224:33)
    at Object.exports.installHooks (/Users/creed/Sites/coinstac-common/node_modules/git-validate/lib/utils.js:248:12)
    at Object.<anonymous> (/Users/creed/Sites/coinstac-common/node_modules/git-validate/bin/install.js:3:7)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Function.Module.runMain (module.js:447:10)
```

**Comment by cdaringe** [comment]
hmmm, i just tried in a [brand new package](https://gist.github.com/cdaringe/9181887fa1e87d9a5e52) it checked out

it may be a npm3 incompatibility?

**Comment by cdaringe** [comment]
git-validate i believe expects a certain package structure. could be playin a role

**Comment by cdaringe** [comment]
@swashcap, i figured this out.  the gist is that `pre-commit` makes a symlink from `.git/hooks/precommit` to your node modules.  however, if your node_modules are scrapped, the link dies.  the fix is to scrap `.git/hooks/precommit` and `node_modules/pre-commit/`... possibly related modules.  re-install and the links are restored
